
-- Add milestone_progress email template
INSERT INTO public.email_templates (template_type, subject, body_html, is_enabled)
VALUES ('milestone_progress', '{{progress}}% Complete!', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="font-family: -apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, ''Helvetica Neue'', Arial, sans-serif; background-color: #f4f4f5; padding: 20px;"><div style="max-width: 500px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1);"><div style="background: linear-gradient(135deg, #1a1a1a, #333); padding: 30px; text-align: center;"><h1 style="color: white; margin: 0; font-size: 28px;">{{progress}}% Complete!</h1></div><div style="padding: 30px;"><p style="color: #1e293b; margin: 0 0 16px;">Hi {{name}},</p><p style="color: #475569; margin: 0 0 16px;">{{milestone_message}}</p><p style="color: #475569; margin: 0 0 16px;">Super excited for our ongoing collaboration on this project!</p><p style="color: #475569; margin: 0 0 8px;">We will be in contact again soon!</p><p style="color: #475569; margin: 0;">Kind regards,<br><strong>Sited Team</strong><br><a href="https://sited.co" style="color: #3b82f6;">https://sited.co</a></p></div></div></body></html>', true)
ON CONFLICT DO NOTHING;

-- Add milestone_progress automation
INSERT INTO public.email_automations (automation_type, is_enabled, settings)
VALUES ('milestone_progress', true, '{"milestones": [25, 50, 75, 100], "messages": {"25": "Great news! We are making solid progress on your project. The foundations are being laid and things are coming together nicely.", "50": "We are halfway there! Your project is taking shape and we are excited about the progress. Keep an eye out for updates!", "75": "We are on the home stretch! Progress is being made hourly, please keep on the lookout for emails from us if there is information we may need to gather for integrations, etc!", "100": "Your project is complete! We are thrilled with the final result and hope you are too. Welcome to your new digital home!"}}')
ON CONFLICT DO NOTHING;
